CREATE DATABASE IF NOT EXISTS healthnet;
USE healthnet;

CREATE TABLE IF NOT EXISTS healthnet_facility_types (
    id INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL,
    description VARCHAR(255),
    seeded BIT(1) NOT NULL DEFAULT 1,
    time_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    time_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS healthnet_facilities (
    id INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    active BIT(1) NOT NULL DEFAULT 1,
    address1 VARCHAR(255) NOT NULL,
    address2 VARCHAR(255),
    phone VARCHAR(16) UNIQUE NOT NULL,
    tenancy_id INT(11) UNSIGNED NOT NULL,
    type INT(11) UNSIGNED NOT NULL,
    time_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    time_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT facility_tenancy FOREIGN KEY (tenancy_id) REFERENCES sugar_tenancies (id),
    CONSTRAINT facility_type FOREIGN KEY (type) REFERENCES healthnet_facility_types (id)
);

CREATE TABLE IF NOT EXISTS healthnet_persistent_logins (
    username VARCHAR(64) NOT NULL,
    series VARCHAR(64) NOT NULL,
    token VARCHAR(64) NOT NULL,
    last_used timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (series)
);